### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by redmarverick** [redmarverick/MMDB#25]
Project Link: https://github.com/redmarverick/MMDB/projects/1
My group is me and @mpa-mxiang

**Comment by divinecharlotte** [comment]
Hi @Team      , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Descriptive issue 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [x] As you are a team of two kindly consider making sure that all cards with the Student C suffix on the template are removed from your copy. after doing so make sure that the number of cards on board remains equal to 15 to make sure that you remain only with the tasks you are required to work on as a team of two

- [x]  Kindly make sure to assign the task cards to the team members, so we should see a circle with the user's avatar on each card. See the example below:

<img width="361" alt="Screen Shot 2023-05-22 at 18 24 04" src="https://github.com/redmarverick/MMDB/assets/60146030/95da2958-a1ce-4390-9cbb-7647e7efd504">


_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danmainah** [comment]
Hi @Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

✔️ Kanban board setup correctly with all cards assigned to team members
✔️ Good issue Description with correct info and link

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
